topics:
  publishers:
    - name: "gps"
      type: std_msgs/msg/String
      qos: 10
      frequency: 5.0
    - name: "topic2"
      type: std_msgs/msg/String
      qos: 10
      frequency: 5.0
  subscribers: 
    - name: "topic2"
      type: std_msgs/msg/String
      qos: 10
      frequency: 5.0
      callback: "print_hi"

robot_id: r1